/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ColumnType } from "./utils/type-utils";
export namespace Components {
    interface TrackGridContainer {
        "col": ColumnType;
        "space": ColumnType;
    }
    interface TrackGridItem {
        "l": number;
        "md": number;
        "s": number;
    }
}
declare global {
    interface HTMLTrackGridContainerElement extends Components.TrackGridContainer, HTMLStencilElement {
    }
    var HTMLTrackGridContainerElement: {
        prototype: HTMLTrackGridContainerElement;
        new (): HTMLTrackGridContainerElement;
    };
    interface HTMLTrackGridItemElement extends Components.TrackGridItem, HTMLStencilElement {
    }
    var HTMLTrackGridItemElement: {
        prototype: HTMLTrackGridItemElement;
        new (): HTMLTrackGridItemElement;
    };
    interface HTMLElementTagNameMap {
        "track-grid-container": HTMLTrackGridContainerElement;
        "track-grid-item": HTMLTrackGridItemElement;
    }
}
declare namespace LocalJSX {
    interface TrackGridContainer {
        "col"?: ColumnType;
        "space"?: ColumnType;
    }
    interface TrackGridItem {
        "l"?: number;
        "md"?: number;
        "s"?: number;
    }
    interface IntrinsicElements {
        "track-grid-container": TrackGridContainer;
        "track-grid-item": TrackGridItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "track-grid-container": LocalJSX.TrackGridContainer & JSXBase.HTMLAttributes<HTMLTrackGridContainerElement>;
            "track-grid-item": LocalJSX.TrackGridItem & JSXBase.HTMLAttributes<HTMLTrackGridItemElement>;
        }
    }
}
