/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ColumnType } from "./components/track-grid-container/track-grid-container";
export namespace Components {
    interface TrackGridContainer {
        "col": ColumnType;
    }
}
declare global {
    interface HTMLTrackGridContainerElement extends Components.TrackGridContainer, HTMLStencilElement {
    }
    var HTMLTrackGridContainerElement: {
        prototype: HTMLTrackGridContainerElement;
        new (): HTMLTrackGridContainerElement;
    };
    interface HTMLElementTagNameMap {
        "track-grid-container": HTMLTrackGridContainerElement;
    }
}
declare namespace LocalJSX {
    interface TrackGridContainer {
        "col"?: ColumnType;
    }
    interface IntrinsicElements {
        "track-grid-container": TrackGridContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "track-grid-container": LocalJSX.TrackGridContainer & JSXBase.HTMLAttributes<HTMLTrackGridContainerElement>;
        }
    }
}
